server:
  port: 8080
contextPath: /

spring:
  datasource:
    url: jdbc:mysql://testdb.cvmb1cvfy5vo.us-east-1.rds.amazonaws.com:3306/autos
    username: root
    password: rootroot
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      connection-timeout: 60000
      pool-name: notification-pool
      minimum-idle: 2
  jpa:
    properties:
       hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect



